### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by sandeepny441** [pradeepsf729/pandas_101#21]
import pandas as pd

# Sample DataFrame for pet stores in the US
data = {
    'Store_ID': [1001, 1002, 1003, 1004, 1005],
    'Store_Name': ['Pet Paradise', 'Animal Kingdom', 'Furry Friends', 'Pet Pals', 'Fauna House'],
    'Location': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Speciality': ['Fish', 'Birds', 'Dogs', 'Cats', 'Reptiles'],
    'Rating': [4.5, 4.2, 3.9, 4.7, 4.0]
}

df_pet_stores = pd.DataFrame(data)

#rename_questiopns

1. How can you rename the column 'Speciality' to 'Pet_Type'?
2. If you wanted to change 'Store_Name' to 'Pet_Store_Name' and 'Rating' to 'Customer_Rating', how would you achieve this using the rename method?
3. Can the rename method be used to change the index names? If so, demonstrate how.
4. How would you use the rename method to change the name of the store with Store_ID 1003?
5. Is there a way to use the rename method to change column names to lowercase?

**Comment by pradeepsf729** [comment]
How would you use the rename method to change the name of the store with Store_ID 1003?

This can be done with replace method right? not rename
Because with rename, we can change the values of column or index, not the actual cell values right?
