### ISSUE TITLE
.iloc 15 Questions

### ISSUE THREAD

**Issue by sandeepny441** [pradeepsf729/pandas_101#4]
import pandas as pd
data = {}

data['A'] = list(range(10))
data['B'] = list(range(10, 20))
data['C'] = list(range(20, 30))

df1 = pd.DataFrame(data)
df1.head()

How would you use .iloc to get the first row of the DataFrame?

How would you use .iloc to get the last row of the DataFrame?

How would you use .iloc to get the first 3 rows and the first 2 columns?

How would you use .iloc to get the last 2 rows and last 2 columns?

How would you use .iloc to get all the rows but only the first column?

How would you use .iloc to get all the columns but only the third row?

How would you use .iloc to get rows from index 4 to index 6, inclusive, and only the second column?

How would you use .iloc to get the value at the fifth row and third column?

How would you use .iloc to get all rows for columns at index 0 and index 2?

How would you use .iloc to update the value at the first row and first column to 99?

How would you use .iloc to set all values in the last column to 0?

How would you use .iloc to swap the first and last rows?

How would you use .iloc to reverse the order of rows?

How would you use .iloc to get rows where the index is even and only the first column?

How would you use .iloc to get rows from index 2 to index 8 but only for columns at index 1 and index 2?

**Comment by pradeepsf729** [comment]
Fixed in https://github.com/pradeepsf729/pandas_101/pull/5

**Comment by sandeepny441** [comment]
-------------------------------------- iLoc

iLOC is purely integer based indexing.
iloc follows Python based position-based indexing unlike LOC.

**Comment by sandeepny441** [comment]
chained indexing - pitfalls 
if we dont use .loc, we might be working on a copy of the dataframe, so the results might not be reflecting the intention. So its better to use .loc when we use chained indexing
When these operations are chained, you might be working on a copy of the data (not always, it depends on the memory layout), so any changes you make don't affect the original Data Frame. On the other hand, loc ensures that you're working directly on the original Data Frame, making assignments as expected.

Ex - 

import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
print("Original DataFrame:")
print(df)

# Attempt to update a value using chained indexing
df[df['A'] == 2]['B'] = 50

if you check df here, it wont show 50 in it 

To make sure the insertion is retained, we need to use .loc
# Update a value using. loc
df.loc[df['A'] == 2, 'B'] = 50

df will have 50 in it now.
